adaptive_lr: false
adversary: false
desired_kl: 0.01
device: cuda:0
dstb_pretrain: 20
end_criterion: null
ent_coef: 0.005
force_floor: 0.3
force_init: 0.5
force_max: 50.0
force_ramp_frac: 0.55
fwd_force: 15.0
l_anneal_steps: 0
l_hold_steps: 20000000
load: null
load_tensornorm: null
lr: 0.0003
max_std: null
net: 512,256,128
no_wandb: false
norm_freeze_steps: 5000000
num_envs: 4096
out: /home/duynguyen/SAFE/safe_mjlab_zoo/runs
reset_log_std: null
reset_value: false
seed: 0
std_ceil: null
std_floor: null
steps: 150000000
target_kl: null
task: go2_walker_flat
terminal_type: all
vf_coef: 0.5
video_interval: 10000000
wandb_project: robot_safety_sandbox
